version: '3'
name: uta
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./user_templates_api/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./user_templates_api/nginx/conf.d/user-templates.conf:/etc/nginx/conf.d/user-templates.conf
    ports:
      - "5001:5001"
    depends_on:
      - web
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: bash -c "docker/user_templates_api/start.sh"
    volumes:
#     - This line should mount the host machine's user information into the container
      - ./user_templates_api:/code/docker/user_templates_api
      - ../src:/code
#     - This line should mount root_dir of main_storage onto docker container
